agent:
  namespace: jenkins-worker

controller:
  additionalPlugins:
    - authorize-project
    - blueocean
    - browserstack-integration
    - build-failure-analyzer
    - docker-workflow
    - github-checks
    - google-container-registry-auth
    - google-login
    - kubernetes-credentials-provider
    - matrix-auth
    - timestamper
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
  ingress:
    enabled: true
  image:
    tag: lts-jdk11
